// vim: set syntax=asciidoc:
[[create]]
== Creating Images
:data-uri:
:toc:
:toclevels 4:
:homepage https://github.com/projectatomic/container-best-practices:

=== Dockerfiles

==== Location

Upstream Dockerfiles should be hosted in a public GIT repository, for example https://github.com[GitHub]. Ideally, the repository should be created under the organization relevant to a particular project. For example, http://www.softwarecollections.org[Software Collections] Dockerfiles are available under the GitHub https://github.com/sclorg[sclorg] organization.

==== Images

Upstream Docker images, such as CentOS and Fedora base images and layered images based on these, should be publicly available on https://registry.hub.docker.com/[Docker Hub].

For details on using the Docker Hub registry, see https://docs.docker.com/userguide/dockerimages/[Docker User Guide].

==== Content

Docker is a platform that enables applications to be quickly assembled from components. When creating Docker images, think about the added value you can provide potential users with. The intention should always be bringing some added functionality on top of plain package installation.

As an example, take this https://github.com/docker-library/wordpress/blob/618490d4bdff6c5774b84b717979bfe3d6ba8ad1/apache/Dockerfile[Word Press Dockerfile]. After running the image and linking it with a database image such as mysql, you will get a fully operational Word Press instance. In addition, you can also specify an external database.

This exactly is the purpose of using Docker images; instead of laborious installation and configuration of separate components, you simply pull an image from a registry, acquiring a set of tools ready to be used right out-of-the-box.

==== Enabling Necessary Repositories

TBD

// maybe move somewhere RHEL-specific

==== Clearing the yum Caches

To keep images as small as possible, it is beneficial to clear the temporary yum cache files after installing or updating packages. To remove unnecessary cache files, use the **yum clean** command. The command is described in detail in the +yum(8)+ man page.

Cache needs to be cleaned out of every layer that updates or installs software. That means if you perform multiple install operations within one layer, you need to run **yum clean** at the end of it. For example:

----
RUN yum install -y epel-release && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 && \
    yum install -y --setopt=tsflags=nodocs bind-utils gettext iproute\
    v8314 mongodb24-mongodb mongodb24 && \
    yum clean all
----

On the other hand, if you perform multiple install/update operations on multiple layers, **yum clean** must be run on each layer. For example:

----
RUN yum install -y epel-release && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 && \
    yum clean all

RUN yum install -y --setopt=tsflags=nodocs bind-utils gettext iproute\
    v8314 mongodb24-mongodb mongodb24 && \
    yum clean all
----

==== Installing Documentation

Because you want to keep the image as small as possible, you can avoid installing documentation files along with installing or updating software by specifying the **nodocs** flag. For example:

----
RUN yum install -y mysql --setopt=tsflags=nodocs
----

==== Updating Software supplied by Base-Image

Avoid updating software supplied by base-image unless necessary. Base images themselves are meant to be updated on a regular basis by the supplier and provide software that has been tested for a particular environment.

Also, updating base-image software in layered images can introduce unexpected problems or bring in unwanted dependencies and in certain cases significantly expand the image size.

In other words, avoid using instructions similar to this one:

----
RUN yum -y update
----

// TBD: different recommendations for Fedora and CentOS/RHEL base images?

==== Users
TBD

==== Working Directory
TBD

==== Exposing Ports

The +EXPOSE+ instruction declares the ports on which a container will listen for incoming connections. You should specify ports your application commonly uses; for example, as seen in this https://github.com/openshift/mysql/blob/master/5.5/Dockerfile[mysql] example:

----
EXPOSE 3306
----

IMPORTANT: The TCP/IP port numbers below 1024 are special in that normal users are not allowed to bind on them.

Therefore, for example for Apache server, ports 8080 or 8433 (HTTP or HTTPS) should be exposed. Otherwise, only the root user will be allowed to run Apache server inside a container.


// For information on exposing ports in Software Collection images, see the xref:software_collections[Software Collections] chapter.

==== Logging
TBD

...

=== Dockerfile Instructions

This chapter provides a list of Docker Instructions with a short explanation and preferred usage.

==== General Usage

===== MAINTAINER

Use the +MAINTAINER+ instruction to set the _Author_ field of the generated images. As most projects are maintained by more than one person, it is preferable to use a universal contact, such as _mailing list address_, _bug tracking mechanism URL_ or _URL of a project_ rather than a real person's name. Generic contact ensures consistency, allows for addressing problems in an appropriate manner and does not discourage potential contributors from collaborating by being too specific.

===== LABEL

Supported in Docker 1.6 and later, +LABEL+ is meant to store metadata about images and containers in key-value pairs. +LABELs+ should provide additional information about images and containers, indexing, searching and should be used to annotate the Docker images and containers. +LABEL+ can also be used to provide useful information to projects that catalogize or utilize Docker images, such as Satellite, OpenShift or Atomic.

NOTE: Do not get +LABEL+ mistaken with +ENV+ -- some projects, for example OpenShift, might use +ENV+ to provide metadata temporarily, until +LABEL+ is not fully supported across operating systems.

The following snippet shows usage of +LABEL+:

----
LABEL MYSQL_VERSION           5.5
LABEL IMAGE_DESCRIPTION       MySQL 5.5
LABEL IMAGE_TAGS              mysql,mysql55
LABEL IMAGE_EXPOSE_SERVICES   3306:mysql
----

====== Mandatory LABELs

The following +LABELs+ should always be part of your Dockerfile. TBD


===== ENTRYPOINT vs CMD

+ENTRYPOINT+ defines the default binary with which the Docker container will start. In other words, it makes the container behave like a binary. The default +ENTRYPOINT+ for Docker is +/bin/sh -c+. Consider the following example:

----
docker run -i -t fedora /bin/bash
----

Here +/bin/bash+ is passed as argument to the +ENTRYPOINT+ which is +/bin/sh -c+. Docker also provides a way to override the entrypoint by providing the --entrypoint flag.

----
docker run --entrypoint /bin/cat -i -t fedora /etc/redhat-release
----

In the example above, the default +ENTRYPOINT+ is overridden by the flag and +/etc/redhat-release+ is passed as a parameter to +/bin/cat+.

+CMD+ is used to execute the supplied command as a parameter to the +ENTRYPOINT+. It is advisable to use +CMD+ unless you are absolutely sure about changing the +ENTRYPOINT+ since all the execution will run as the parameter to the +ENTRYPOINT+. Using +ENTRYPOINT+ can easily confuse the other users who are not familiar with the image and can make debugging or even obtaining a shell difficult since everything will be a parameter to the +ENTRYPOINT+

CMD Example:
----
CMD ["python","myscript.py"]
----

ENTRYPOINT Example:
----
ENTRYPOINT ["/usr/bin/python"]
----


==== systemd

tbd

==== non-systemd

tbd

=== Layering

This chapter provides guidelines on creating layers.

==== Minimizing the Number of Layers

In general, having fewer layers improves readability. Commands that are chained together become a part of the same layer. To reduce the number of layers, chain commands together. Find a balance, though, between a large number of layers (and a great many commands), and a small number of layers (and obscurity caused by brevity).

A new layer is created for every new instruction defined. This does not necessarily mean that one instruction should be associated with only one command or definition.

Ensure transparency and provide a good overview of the content of each layer by grouping related operations together so that they together constitute a single layer. Consider this snippet from the OpenShift Python 3.3 Dockerfile:

----
RUN yum install -y \
    https://www.softwarecollections.org/en/scls/rhscl/python33/epel-7-x86_64/download/rhscl-python33-epel-7-x86_64.noarch.rpm && \
    yum install -y --setopt=tsflags=nodocs --enablerepo=centosplus \
    python33 python33-python-devel python33-python-setuptools \
    epel-release && \
    yum install -y --setopt=tsflags=nodocs install nss_wrapper && \
    yum clean all -y && \
    scl enable python33 "easy_install pip" && \
    chown -R default:default /opt/openshift && \
    chmod -R og+rwx /opt/openshift
----

Each command that is related to the installation and configuration of `sti-python` is grouped together as a part of the same layer. This meaningful grouping of operations keeps the number of layers low while keeping the easy legibility of the layers high.

// Find a good example for the opposite case, when we want to have similar operations split into multiple instructions.

==== Squashing Layers

tbd

=== References

// References to external sites and project-specific guidelines.

Please see the following resources for more information on the Docker container technology and project-specific guidelines.

http://docs.docker.com/[Docker Documentation] -- Detailed information about the Docker platform.

https://github.com/openshift/openshift-docs/blob/master/creating_images/guidelines.adoc#openshift-specific-guidelines[OpenShift Guidelines] -- Guidelines for creating images specific to the OpenShift project.
