// vim: set syntax=asciidoc:
[[dockerfile_instructions]]
= Dockerfile Instructions
:data-uri:
:icons:
:toc:
:toclevels 4:
:numbered:
:homepage https://github.com/projectatomic/container-best-practices:

This chapter provides a list of Docker Instructions with a short explanation and preferred usage.

== General Usage

=== MAINTAINER

Use the +MAINTAINER+ instruction to set the _Auhtor_ field of the generated images. This instruction should contain a real person's name rather than the name of a project or organizations. This way, it is easier for the image consumer to reach out to the image owner and address potential problems.

For example:

----
MAINTAINER  Jane Doe <jdoe@redhat.com>
----

=== LABEL

Supported in Docker 1.6 and later, +LABEL+ is meant to store metadata about images and containers in key-value pairs. +LABELs+ should provide additional information about images and containers, indexing, searching and should be used to annotate the Docker images and containers. +LABEL+ can also be used to provide useful information to projects that catalogize or utilize Docker images, such as Satellite, OpenShift or Atomic.

NOTE: Do not get +LABEL+ mistaken with +ENV+ -- some projects, for example OpenShift, might use +ENV+ to provide metadata temporarily, until +LABEL+ is not fully supported across operating systems.

The following snippet shows usage of +LABEL+:

----
LABEL MYSQL_VERSION           5.5
LABEL IMAGE_DESCRIPTION       MySQL 5.5
LABEL IMAGE_TAGS              mysql,mysql55
LABEL IMAGE_EXPOSE_SERVICES   3306:mysql
----

==== Mandatory LABELs

The following +LABELs+ should always be part of your Dockerfile. TBD


=== ENTRYPOINT vs CMD

tbd


== systemd

tbd

== non-systemd

tbd
