// vim: set syntax=asciidoc:
[[dockerfile_instructions]]
= Dockerfile Instructions
:data-uri:
:icons:
:toc:
:toclevels 4:
:numbered:
:homepage https://github.com/projectatomic/container-best-practices:

This chapter provides a list of Docker Instructions with a short explanation and preferred usage.

== General Usage

=== MAINTAINER

Use the +MAINTAINER+ instruction to set the _Author_ field of the generated images. As most projects are maintained by more than one person, it is preferable to use a universal contact, such as _mailing list address_, _bug tracking mechanism URL_ or _URL of a project_ rather than a real person's name. Generic contact ensures consistency, allows for addressing problems in an appropriate manner and does not discourage potential contributors from collaborating by being too specific.

=== LABEL

Supported in Docker 1.6 and later, +LABEL+ is meant to store metadata about images and containers in key-value pairs. +LABELs+ should provide additional information about images and containers, indexing, searching and should be used to annotate the Docker images and containers. +LABEL+ can also be used to provide useful information to projects that catalogize or utilize Docker images, such as Satellite, OpenShift or Atomic.

NOTE: Do not get +LABEL+ mistaken with +ENV+ -- some projects, for example OpenShift, might use +ENV+ to provide metadata temporarily, until +LABEL+ is not fully supported across operating systems.

The following snippet shows usage of +LABEL+:

----
LABEL MYSQL_VERSION           5.5
LABEL IMAGE_DESCRIPTION       MySQL 5.5
LABEL IMAGE_TAGS              mysql,mysql55
LABEL IMAGE_EXPOSE_SERVICES   3306:mysql
----

==== Mandatory LABELs

The following +LABELs+ should always be part of your Dockerfile. TBD


=== ENTRYPOINT vs CMD

+ENTRYPOINT+ defines the default binary with which the Docker container will start. In other words, it makes the container behave like a binary. The default +ENTRYPOINT+ for Docker is +/bin/sh -c+. Consider the following example:

----
docker run -i -t fedora /bin/bash
----

Here +/bin/bash+ is passed as argument to the +ENTRYPOINT+ which is +/bin/sh -c+. Docker also provides a way to override the entrypoint by providing the --entrypoint flag.

----
docker run --entrypoint /bin/cat -i -t fedora /etc/redhat-release
----

In the example above, the default +ENTRYPOINT+ is overridden by the flag and +/etc/redhat-release+ is passed as a parameter to +/bin/cat+.

+CMD+ is used to execute the supplied command as a parameter to the +ENTRYPOINT+. It is advisable to use +CMD+ unless you are absolutely sure about changing the +ENTRYPOINT+ since all the execution will run as the parameter to the +ENTRYPOINT+. Using +ENTRYPOINT+ can easily confuse the other users who are not familiar with the image and can make debugging or even obtaining a shell difficult since everything will be a parameter to the +ENTRYPOINT+

CMD Example:
----
CMD ["python","myscript.py"]
----

ENTRYPOINT Example:
----
ENTRYPOINT ["/usr/bin/python"]
----


== systemd

tbd

== non-systemd

tbd
