// vim: set syntax=asciidoc:
[[general_guidelines]]
= General Guidelines
:data-uri:
:icons:
:toc:
:toclevels 4:
:numbered:
:homepage https://github.com/projectatomic/container-best-practices:

== Content
TBD

== Updating Base Image Software

Updating base-image software is a common practice in many Dockerfiles:

----
yum -y update && yum -y clean all
----

However, before doing so, you should first consider whether updating base-image software would be really beneficial and bring any added value. 
Updating software can introduce unexpected problems or bring in unwanted dependencies and in certain cases significantly expand the image size. Base images themselves are meant to be updated on a regular basis and provide software that has been tested for the particular environment, so there is no need for running additional updates.

TBD: different recommendations for Fedora, CentOS/RHEL base images?

== Users
TBD

== Working Directory
TBD

== Exposing Ports

Important ports should always be exposed using the +EXPOSE+ instruction in a Dockerfile. The +EXPOSE+ instruction declares the ports on which a container will listen for connections. You should specify ports your application commonly uses, for example the Dockerfile for an image containing MongoDB would use:

----
EXPOSE 27017
----

// For information on exposing ports in Software Collection images, see the xref:software_collections[Software Collections] chapter.

== Logging
TBD

...
