// vim: set syntax=asciidoc:
[[general_guidelines]]
= General Guidelines
:data-uri:
:icons:
:toc:
:toclevels 4:
:numbered:
:homepage https://github.com/projectatomic/container-best-practices:

== Content
TBD

=== Documentation

Because you want to keep the image as small as possible, you can avoid installing documentation files along with installing or updating software by specifying the **nodocs** flag. For example:

----
RUN yum -y update --setopt=tsflags=nodocs
----

== Updating Base-Image Software

Avoid updating base-image software unless necessary. Base images themselves are meant to be updated on a regular basis by the supplier and provide software that has been tested for a particular environment.

Also, updating base-image software in layered images can introduce unexpected problems or bring in unwanted dependencies and in certain cases significantly expand the image size.

In other words, avoid using instructions similar to this one:

----
RUN yum -y update
----

// TBD: different recommendations for Fedora and CentOS/RHEL base images?

== Users
TBD

== Working Directory
TBD

== Exposing Ports

The +EXPOSE+ instruction declares the ports on which a container will listen for incoming connections. You should specify ports your application commonly uses; for example, as seen in this https://github.com/openshift/mysql/blob/master/5.5/Dockerfile[mysql] example:

----
EXPOSE 3306
----

IMPORTANT: The TCP/IP port numbers below 1024 are special in that normal users are not allowed to bind on them.

Therefore, for example for Apache server, ports 8080 or 8433 (HTTP or HTTPS) should be exposed. Otherwise, only the root user will be allowed to run Apache server inside a container.


// For information on exposing ports in Software Collection images, see the xref:software_collections[Software Collections] chapter.

== Logging
TBD

...
