// Atomic https://github.com/projectatomic/atomic

The https://github.com/projectatomic/atomic[atomic application] is meant to be a user-friendly way to
install, manage, and run container images using container. Unlike docker commands, it leverages the ability to
read and act upon LABELs defined in a Dockerfile.  By its nature, it helps authors of Dockerfiles to have
their images run as they intended without a significant amount of knowledge by the end users.  Atomic has several
subcommands:

* diff
* link:help[help]
* host
* info
* install
* images
* migrate
* mount
* push
* scan
* stop
* run
* top
* uninstall
* unmount
* update
* version
* verify

Knowledge of these subcommands can make you a better author of Dockerfiles because you too can simplify end users'
interactions with your images.  Look to the following sections for more information on these relevant subcommands.


[[help]]

==== Displaying the help file

You can display the help file for a container using the **https://github.com/projectatomic/atomic[atomic]** command.
For example, to display the help file for a container called _foobar_, you would run the command:

[source, none]
----
# atomic help foobar
----
This is the default method of displaying the help file.  In this case, the help file is formatted like any typical
man page and is displayed (like man) with a pager.  The help file needs to be located in the / of the image filesystem
and called *help.1*.

If no help file is present and there is no HELP LABEL defined, atomic will simply tell you it could not find any
help associated with that container or image.
