// vim: set syntax=asciidoc:
[[Overview]]
== Overview
:data-uri:
:homepage https://github.com/projectatomic/container-best-practices:

Container technology is a popular packaging method for developers and system administrators to build, ship and run distributed applications. Production use of image-based container technology requires a disciplined approach to development. This document provides guidance and recommendations for creating and managing images to control application lifecycle.

In link:#plan[*Application Planning*] we discuss how to deconstruct applications into microservices, common types of images and how planning must consider the target deployment platforms.

link:#create[*Creating Images*] discusses the details about how to work with Dockerfiles, best practices, tips and tricks, and tools available to developers.

The link:#build[*Build*] section discusses the importance of automation in building, testing and maintaining images. We discuss ideal workflows, how to plan a test environment, types of testing and image certification.

Finally, *Delivery* covers how to get images and updates to the end-users, whether that's inside an enterprise or public infrastructure. A key consideration is access control.

=== Content of the Containers is Important

When talking about containers, content is a very important thing. The content is important especially when we compare linux container technology with a classic virtual machine. Both is basically a kind of virtualization for isolating applications, but we cannot consider containers to be the same as virtual machines if it is related to security.

The big difference between linux containers and a virtual machine is the guest's operating system, because all containers share the kernel with the host. That makes the containers much more efficient, but the fact that the kernel is shared with the host and other containers means, that some unfortunate security flaw in the host kernel creates potential door from the container, which may influence either other containers or the host itself.

That all makes the content of the container very important, because running a malicious container is always a big risk for the host machine. Every container user is advised to pay attention at what containers are running in the infrastructure.
