// vim: set syntax=asciidoc:
[[Overview]]
== Overview
:data-uri:
:homepage https://github.com/projectatomic/container-best-practices:

=== Abstract

Container technology is a popular packaging method for developers and system administrators to build, ship and run distributed applications. Production use of image-based container technology requires a disciplined approach to development and writing Dockerfiles and defining containerized applications can become rather complex. Therefore, we're passing on our experience in this document, which aims to provide guidance and recommendations for creation, deployment and usage of containerized applications.

This guide assumes the reader has at least basic knowledge of the containerization technologies. The document also isn't a reference guide of all the Dockerfile instructions. Should you require this kind of content, the documentation is available on the https://www.docker.com/[Docker website].

// consider adding a references section linking important projects

=== Contributing

This is a continuously evolving work with the source files available on https://github.com/projectatomic/container-best-practices[GitHub]. If you find any inconsistencies, mistakes or typos, please use the https://github.com/projectatomic/container-best-practices/issues[issue tracker] to report them. If you wish to participate, feel free to open a https://github.com/projectatomic/container-best-practices/pulls[pull request].
